name: ci

on:
  push:
    branches: [ main, release/*, feature/* ]
  pull_request:
    branches: [ main, release/* ]

jobs:
  ios:
    runs-on: macos-15
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Build
      run: xcodebuild build -scheme Nats -destination generic/platform=ios
  check-linter:
    runs-on: macos-15
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Install swift-format
      run: brew install swift-format
    - name: Run check
      run: swift-format lint --configuration .swift-format -r --strict Sources Tests
